### ISSUE TITLE
First App Error

### ISSUE THREAD

**Issue by jgerardsimcock** [johanan/Building-Scalable-Apps-with-Redis-and-Node.js#1]
socket.io/?EIO=3&transport=polling&t=1432310264485-41 HTTP/1.1" 404

When just trying to use the websockets with the python server I get this error

**Comment by jgerardsimcock** [comment]
https://github.com/jgerardsimcock/scalable_node_redis/tree/master/socket_app

here is my code

**Comment by johanan** [comment]
Based on the fact that this is Socket.IO and you state it is a first app error I am assuming it is this: https://github.com/johanan/Building-Scalable-Apps-with-Redis-and-Node.js/tree/master/Chapter%202/first%20app

I pulled this down to a new folder and I was able to get it to work. My only thoughts are did you run npm install? Are you serving index.html with anything? The node app is only responding to socket.io requests and not serving any files. I recommend using python -m SimpleHTTPServer or python -m http.server depending on your python version (2 and 3 respectively).

**Comment by barrard** [comment]
on page 106, this authenticated middleware was casuing a bug with an empty redis cache

module.exports.authenticated = function authenticated(req, res, next) {
    req.session.isAuthenticated = req.session.passport.user !== undefined;
........}

i just took off the user key

module.exports.authenticated = function authenticated(req, res, next) {
    req.session.isAuthenticated = req.session.passport !== undefined;
........}

**Comment by yabetse** [comment]
On page 36 ( very simple authentication), 
module.exports.authenticated .... Returns this error
TypeError: Cannot read property 'locals' of undefined

I tried res.app.locals instead but that didn't work too. How do i fix 👆
