### ISSUE TITLE
NodeChat , very simple authentication : undefined error

### ISSUE THREAD

**Issue by yabetse** [johanan/Building-Scalable-Apps-with-Redis-and-Node.js#2]
On page 36 ( very simple authentication),
module.exports.authenticated .... Returns this error. Caused by this assignment statement

> res.locals.isAuthenticated = req.session.isAuthenticated; 

TypeError: Cannot read property 'locals' of undefined at Object.authenticated ....

I tried res.app.locals instead but that didn't work too. How do i fix 👆

**Comment by echeadle** [comment]
Did you add in the code past page 36?  I don't remember many additional functions you need to add past page 36 for things to work, but try putting in the code down through page 38 where it says add in the loginProcess function in index.js.  I think it should work after that.

**Comment by johanan** [comment]
@yabetse, sorry for taking so long. It is easy to get distracted and then a month goes by. I pulled down the code, ran npm install, and then node app.js. I ran into a similar problem that you did. The problem I had was that Redis was not running. I just used Docker to create an instance and everything worked how it should have.
