### ISSUE TITLE
Soft Link on page 49 looks strange

### ISSUE THREAD

**Issue by echeadle** [johanan/Building-Scalable-Apps-with-Redis-and-Node.js#3]
ln –s node_modules/socket.io/node_modules/socket.io-client/socket.io.js

This link does not seem to work.

There is a socket.io.js in node_modules/socket.io-client so I would think the correct link is 

ln -s node_modules/socket.io-client/socket.io.js socket.io.js

This is a fun book.. I am having some issues with the first app doing what it is supposed to do, but the book covers a lot of material and is very informative. Thanks

**Comment by johanan** [comment]
@echeadle you are correct. I have committed the updated link.
